<a href="https://colab.research.google.com/github/SSB2000/ffc-datascience-tutorial/blob/master/ffc_04hr_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys

# Intro to numpy

In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4, 5])

NameError: ignored

In [ ]:
a[0]

1

In [ ]:
a[[0, 2, 3]]

array([1, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array(["shubham", "bohra"])

In [ ]:
a

array(['shubham', 'bohra'], dtype='<U7')

In [ ]:
a.dtype

dtype('<U7')

In [ ]:
a = np.array([1, 2, 3, 4], dtype=np.float64)

In [ ]:
a.dtype

dtype('float64')

Dimensions

In [ ]:
a = np.array([
              [1, 2, 3],
              [3, 2, 1]
])

In [ ]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.ndim

2

In [ ]:
a.size

6

Indexing ans slicing of matrices

In [ ]:
a = np.array([
              [1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
])

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[1][1]

5

In [ ]:
a[1, 1]

5

In [ ]:
a[1:2, :2]

array([[4, 5]])

In [ ]:
a[0:2, :2]

array([[1, 2],
       [4, 5]])

Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a.sum()

15

In [ ]:
a.mean()

3.0

In [ ]:
a.var()

2.0

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([5, 7, 9])

In [ ]:
a.sum(axis=1)

array([ 6, 15])

Broadcasting and vectorized operations

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 10

array([10, 11, 12, 13, 14])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103, 104])

In [ ]:
a = np.arange(5)

In [ ]:
b = np.arange(5)

In [ ]:
a + b

array([0, 2, 4, 6, 8])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a * b

array([ 0,  1,  4,  9, 16])

Boolean Array

In [ ]:
a = np.arange(5)

In [ ]:
a[[True, False, False, False, True]]

array([0, 4])

In [ ]:
a[[0, -1]]

array([0, 4])

In [ ]:
a[0], a[-1]

(0, 4)

In [ ]:
a[a == 0]

array([0])

In [ ]:
a[(a == 0) | (a == 2)]

array([0, 2])

In [ ]:
a[a > a.mean()]

array([3, 4])

Linear Algebra

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
b = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a @ b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Exercise

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.19.5


In [ ]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones([2, 2], dtype=np.int)

array([[1, 1],
       [1, 1]])

In [ ]:
np.ones([3, 2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
X = np.arange(4, dtype=np.int)
np.ones_like(X)

array([1, 1, 1, 1])

In [ ]:
X = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones_like([4, 4], dtype=np.int) * 5

array([5, 5])

In [ ]:
np.ones_like(np.array([[1, 2], [2, 3]], dtype=np.int)) * 7

array([[7, 7],
       [7, 7]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(10, size=3)

array([7, 8, 3])

In [ ]:
# np.random.random((3, 3, 3))
np.random.randn(3, 3, 3)

array([[[ 1.53841213,  0.02573259, -0.89616626],
        [ 0.2922439 ,  0.19515758, -1.05377021],
        [-0.81080673, -1.53309324, -1.65660434]],

       [[-0.21188269, -0.01077956, -0.59712595],
        [ 0.44775025,  0.50845545, -0.31556838],
        [ 0.37238367,  1.54197169,  1.27337805]],

       [[ 0.23281222,  1.83967143, -1.10499191],
        [-0.72796356,  1.84517166, -1.14484515],
        [-0.55551595,  1.05221289,  2.15856009]]])

In [ ]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [ ]:
X = np.array([1, 2, 3])
print(X, id(X))


[1 2 3] 140304380851344


In [ ]:
Y = X.copy()
print(Y, id(Y))

[1 2 3] 140304380661552


In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 11)[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Z = np.zeros((10, 10))
print(Z)
print("%d bytes" % (Z.size * Z.itemsize))b

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


Array Indexation

In [ ]:
X = np.arange(10)
print(X)
print(X[0])
print(X[-1])
print(X[0 : 3])
print(X[1 : -1])
print(X[::-1])
print(X[::2])

[0 1 2 3 4 5 6 7 8 9]
0
9
[0 1 2]
[1 2 3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]


In [ ]:
X = np.array([
              [1, 2, 3],
              [10, 20, 30],
              [100, 200, 300]
])
print(X)
print(X[0])
print(X[-1])
print(X[0][0])
print(X[0, 0])
print(X[-1][-1])
print(X[-1, -1])
print(X[1 : -1])
print(X[0:2, 0:2])
print(X[:2, :2])
print(X[-2:, -2:])
print(X[1:, 1:])

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
[1 2 3]
[100 200 300]
1
1
300
300
[[10 20 30]]
[[ 1  2]
 [10 20]]
[[ 1  2]
 [10 20]]
[[ 20  30]
 [200 300]]
[[ 20  30]
 [200 300]]


Array Manipulation

In [ ]:
X = [-5, -3, 0, 10, 40, 10]
X = np.array(X, np.float)
print(X)
print(X[::-1])
X.sort()
print(X)
X[4] = 1
print(X)

[-5. -3.  0. 10. 40. 10.]
[10. 40. 10.  0. -3. -5.]
[-5. -3.  0. 10. 10. 40.]
[-5. -3.  0. 10.  1. 40.]


In [ ]:
X = np.array([
  [1,   2,  3,  4],
  [5,   6,  7,  8],
  [9,  10, 11, 12],
  [13, 14, 15, 16]
])
print(X)
X[-1] = np.ones(4)
print(X)
X[-1, -1] = 0
print(X)
X += 5
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  0]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [ 6  6  6  5]]


Boolean Array(masks)

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(X[X <= 0])
print(X[X > 5])
print(X[X > X.mean()])
print(X[(X == 2) | (X == 10)])

[-1  0 -4  0  0 -9]
[ 6 10]
[ 2  5  6 10]
[ 2 10]


Logic Function

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
print(X.all())
print(X.any())

False
True


Summary Statistics

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
print(X.sum())
print(X.mean())

43
4.777777777777778


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(X.sum(axis=0))
print(X.mean(axis=1))
print(X.max(axis=0))

[28 32 36 40]
[ 2.5  6.5 10.5 14.5]
[13 14 15 16]
