<a href="https://colab.research.google.com/github/SSB2000/ffc-datascience-tutorial/blob/master/ffc_04hr_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys

In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a[0]

1

In [ ]:
a[[0, 2, 3]]

array([1, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array(["shubham", "bohra"])

In [ ]:
a

array(['shubham', 'bohra'], dtype='<U7')

In [ ]:
a.dtype

dtype('<U7')

In [ ]:
a = np.array([1, 2, 3, 4], dtype=np.float64)

In [ ]:
a.dtype

dtype('float64')

Dimensions

In [ ]:
a = np.array([
              [1, 2, 3],
              [3, 2, 1]
])

In [ ]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.ndim

2

In [ ]:
a.size

6

Indexing ans slicing of matrices

In [ ]:
a = np.array([
              [1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
])

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[1][1]

5

In [ ]:
a[1, 1]

5

In [ ]:
a[1:2, :2]

array([[4, 5]])

In [ ]:
a[0:2, :2]

array([[1, 2],
       [4, 5]])

Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a.sum()

15

In [ ]:
a.mean()

3.0

In [ ]:
a.var()

2.0

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([5, 7, 9])

In [ ]:
a.sum(axis=1)

array([ 6, 15])

Broadcasting and vectorized operations

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 10

array([10, 11, 12, 13, 14])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103, 104])

In [ ]:
a = np.arange(5)

In [ ]:
b = np.arange(5)

In [ ]:
a + b

array([0, 2, 4, 6, 8])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a * b

array([ 0,  1,  4,  9, 16])

Boolean Array

In [ ]:
a = np.arange(5)

In [ ]:
a[[True, False, False, False, True]]

array([0, 4])

In [ ]:
a[[0, -1]]

array([0, 4])

In [ ]:
a[0], a[-1]

(0, 4)

In [ ]:
a[a == 0]

array([0])

In [ ]:
a[(a == 0) | (a == 2)]

array([0, 2])

In [ ]:
a[a > a.mean()]

array([3, 4])

Linear Algebra

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
b = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a @ b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])